name = "mclx-home-ui-for-browser"
compatibility_date = "2024-01-01"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]

[[pages_builds]]
compatibility_flags = ["nodejs_compat"]
