export type Language = "en" | "bn";

export const LANGUAGES = {
  EN: "en" as const,
  BN: "bn" as const,
} as const;

export const LANGUAGE_NAMES = {
  [LANGUAGES.EN]: "English",
  [LANGUAGES.BN]: "বাংলা",
} as const;

export const TRANSLATIONS = {
  [LANGUAGES.EN]: {
    // Settings Menu
    settings: "Settings",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    language: "Language",
    english: "English",
    bangla: "বাংলা",
    autoOrderTabs: "Auto Order Tabs",
    showClock: "Show Clock",
    showRightSidebar: "Show Right Sidebar",
    enableLeftSidebarHover: "Left Hover Open",
    resizeShortcuts: "Resize Shortcuts",
    backgroundImage: "Background Image",
    clockSetting: "Clock Setting",
    clockPosition: "Clock Position",
    searchEngine: "Search Engine",
    searchHistory: "Search History",
    history: "History",
    historyDescription:
      "Recent searches and shortcut opens appear here in one timeline.",
    noHistory: "No history yet",
    historyEmptyDescription:
      "Your searches and opened shortcuts will show up here.",
    searchEntry: "Search",
    shortcutEntry: "Shortcut",
    noSearchHistory: "No recent searches yet",
    layoutMode: "Layout Mode",
    layoutDefault: "Default",
    layoutCompact: "Compact",
    layoutFocus: "Focus",
    google: "Google",
    duckduckgo: "DuckDuckGo",
    bing: "Bing",
    brave: "Brave",
    shortcutActions: "SHORTCUT ACTIONS",
    dashboardConfig: "DASHBOARD CONFIG",
    deleteShortcut: "delete",
    clockSettings: "Clock Settings",
    shortcutPosition: "Shortcut Position",
    top: "Top",
    center: "Center",
    bottom: "Bottom",
    dynamicWallpaper: "Dynamic Wallpaper",
    profileShare: "Profile Share",
    exportProfile: "Export Profile",
    importProfile: "Import Profile",
    importProfileConfirmTitle: "Import Shared Profile?",
    importProfileConfirmDescription:
      "This will replace your current tabs and settings. Your background will stay unchanged.",
    profileImportInvalid: "Invalid profile JSON file.",
    profileImportSuccess: "Shared profile imported successfully.",
    profileImportFailed: "Failed to apply shared profile.",
    profileExportFailed: "Failed to export profile file.",



    // Clock
    clock: "Clock",

    // Notepad
    notepad: "Notepad",
    notes: "Notes",
    stickyNotes: "Sticky Notes",
    stickyNoteTitle: "Sticky Note Title",
    searchStickyNotes: "Search sticky notes...",
    noStickyNotesFound: "No sticky notes found",
    untitledStickyNote: "Untitled Sticky Note",
    noStickyContent: "No content...",
    savedStatus: "Saved",
    setReminder: "Set Reminder",
    clearReminder: "Clear Reminder",
    hours: "Hours",
    minutes: "Minutes",
    hoursShort: "h",
    minutesShort: "m",
    scheduled: "Scheduled",
    overdue: "Overdue",
    reminderMax24h: "Reminder must be between 1 minute and 24 hours.",
    reminderInvalidNumbers: "Please enter valid hours and minutes.",
    reminderSetFailed: "Failed to set reminder.",
    deleteStickyNoteTitle: "Delete Sticky Note?",
    deleteStickyNoteDescriptionPrefix: "Are you sure you want to delete",
    thisStickyNote: "this sticky note",
    stickyAlarmTitle: "Sticky Note Alarm",
    reminderDefaultMessage: "Your sticky note reminder is due now.",
    soundBlockedHint: "Browser blocked sound autoplay for this alarm video.",
    tapToUnmute: "Tap to unmute",
    dismissAlarm: "Dismiss",
    openStickyNote: "Open Sticky Note",
    turnOffAlarm: "Turn Off Alarm",
    alarmLeaveWarning: "An alarm is currently running. Turn it off before leaving.",
    projects: "Projects",
    clear: "Clear",
    writeYourNotesHere: "Write your notes here...",

    // Projects
    noProjectsYet: "No projects yet",
    createFirstProject:
      "Create your first project to start organizing your tasks",
    addProject: "Add Project",
    createNewProject: "Create New Project",
    projectTitle: "Project Title",
    enterProjectTitle: "Enter project title...",
    description: "Description (Optional)",
    enterProjectDescription: "Enter project description...",
    createProject: "Create Project",
    cancel: "Cancel",
    editProject: "Edit Project",
    saveChanges: "Save Changes",
    deleteProject: "Delete Project",
    areYouSureDeleteProject: "Are you sure you want to delete",
    thisActionCannotBeUndone: "This action cannot be undone.",

    // Todos
    addNewTodo: "Add a new todo...",
    noTodosYet: "No todos yet. Add one above!",
    addTodo: "Add Todo",
    low: "Low",
    medium: "Medium",
    high: "High",
    progress: "Progress",
    completed: "completed",

    // Tabs
    shortcuts: "Shortcuts",
    startByAddingFirstShortcut: "Start by adding your first shortcut.",
    addShortcut: "Add Shortcut",
    shortcutOptions: "Shortcut options",
    keyboardShortcut: "Keyboard Shortcut",
    recordShortcut: "Record Shortcut",
    pressKeys: "Press any key combination...",
    shortcutInUse: "This shortcut is already in use",
    clearShortcut: "Clear Shortcut",
    openInNewWindow: "Open in new window",
    setShortcutDescription:
      "Set a keyboard shortcut for quick access to this tab.",
    shortcut: "Shortcut",
    resetEverything: "Reset Everything",
    resetEverythingDescription:
      "This will clear all tabs, projects, notes, and settings. This action cannot be undone.",
    confirmReset: "Are you sure you want to reset everything?",
    resetWarning:
      "This will permanently delete all your data including tabs, projects, notes, and settings.",

    // Common
    loading: "Loading...",
    error: "Error",
    success: "Success",
    close: "Close",
    save: "Save",
    edit: "Edit",
    add: "Add",
    remove: "Remove",
    update: "Update",
    create: "Create",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    refresh: "Refresh",
    back: "Back",
    next: "Next",
    previous: "Previous",
    finish: "Finish",
    done: "Done",
    ok: "OK",
    yes: "Yes",
    no: "No",
  },

  [LANGUAGES.BN]: {
    // Settings Menu
    settings: "সেটিংস",
    theme: "থিম",
    light: "আলো",
    dark: "অন্ধকার",
    system: "সিস্টেম",
    language: "ভাষা",
    english: "English",
    bangla: "বাংলা",
    autoOrderTabs: "অটো অর্ডার ট্যাব",
    showClock: "ঘড়ি দেখান",
    showRightSidebar: "ডান সাইডবার দেখান",
    enableLeftSidebarHover: "বাম হোভার ওপেন",
    resizeShortcuts: "শর্টকাট রিসাইজ",
    backgroundImage: "ব্যাকগ্রাউন্ড ইমেজ",
    clockSetting: "ঘড়ি সেটিং",
    clockPosition: "ঘড়ির অবস্থান",
    searchEngine: "সার্চ ইঞ্জিন",
    searchHistory: "সার্চ হিস্টোরি",
    history: "হিস্টোরি",
    historyDescription:
      "সাম্প্রতিক সার্চ এবং খোলা শর্টকাট এখানে একসাথে দেখাবে।",
    noHistory: "এখনো কোনো হিস্টোরি নেই",
    historyEmptyDescription:
      "আপনার সার্চ এবং খোলা শর্টকাট এখানে দেখা যাবে।",
    searchEntry: "সার্চ",
    shortcutEntry: "শর্টকাট",
    noSearchHistory: "এখনো কোনো সাম্প্রতিক সার্চ নেই",
    layoutMode: "লেআউট মোড",
    layoutDefault: "ডিফল্ট",
    layoutCompact: "কম্প্যাক্ট",
    layoutFocus: "ফোকাস",
    google: "Google",
    duckduckgo: "DuckDuckGo",
    bing: "Bing",
    brave: "Brave",
    shortcutActions: "SHORTCUT ACTIONS",
    dashboardConfig: "DASHBOARD CONFIG",
    deleteShortcut: "delete",
    clockSettings: "ঘড়ি সেটিং",
    shortcutPosition: "শর্টকাট অবস্থান",
    top: "উপরে",
    center: "কেন্দ্রে",
    bottom: "নিচে",
    dynamicWallpaper: "ডাইনামিক মিডিয়া",
    profileShare: "প্রোফাইল শেয়ার",
    exportProfile: "প্রোফাইল এক্সপোর্ট",
    importProfile: "প্রোফাইল ইমপোর্ট",
    importProfileConfirmTitle: "শেয়ার করা প্রোফাইল ইমপোর্ট করবেন?",
    importProfileConfirmDescription:
      "এটি আপনার বর্তমান শর্টকাট ও সেটিংস প্রতিস্থাপন করবে। ব্যাকগ্রাউন্ড অপরিবর্তিত থাকবে।",
    profileImportInvalid: "অবৈধ প্রোফাইল JSON ফাইল।",
    profileImportSuccess: "শেয়ার করা প্রোফাইল সফলভাবে ইমপোর্ট হয়েছে।",
    profileImportFailed: "শেয়ার করা প্রোফাইল প্রয়োগ করা যায়নি।",
    profileExportFailed: "প্রোফাইল এক্সপোর্ট করা যায়নি।",



    // Clock
    clock: "ঘড়ি",

    // Notepad
    notepad: "নোটপ্যাড",
    notes: "নোট",
    stickyNotes: "স্টিকি নোট",
    stickyNoteTitle: "স্টিকি নোট শিরোনাম",
    searchStickyNotes: "স্টিকি নোট খুঁজুন...",
    noStickyNotesFound: "কোনো স্টিকি নোট পাওয়া যায়নি",
    untitledStickyNote: "শিরোনামহীন স্টিকি নোট",
    noStickyContent: "কোনো কনটেন্ট নেই...",
    savedStatus: "সেভড",
    setReminder: "রিমাইন্ডার সেট করুন",
    clearReminder: "রিমাইন্ডার মুছুন",
    hours: "ঘন্টা",
    minutes: "মিনিট",
    hoursShort: "ঘ",
    minutesShort: "মি",
    scheduled: "নির্ধারিত",
    overdue: "সময় পেরিয়ে গেছে",
    reminderMax24h: "রিমাইন্ডার ১ মিনিট থেকে ২৪ ঘন্টার মধ্যে হতে হবে।",
    reminderInvalidNumbers: "সঠিক ঘন্টা ও মিনিট দিন।",
    reminderSetFailed: "রিমাইন্ডার সেট করা যায়নি।",
    deleteStickyNoteTitle: "স্টিকি নোট মুছবেন?",
    deleteStickyNoteDescriptionPrefix: "আপনি কি নিশ্চিত যে আপনি মুছতে চান",
    thisStickyNote: "এই স্টিকি নোট",
    stickyAlarmTitle: "স্টিকি নোট এলার্ম",
    reminderDefaultMessage: "আপনার স্টিকি নোট রিমাইন্ডারের সময় হয়েছে।",
    soundBlockedHint: "ব্রাউজার এই ভিডিওর সাউন্ড অটোপ্লে ব্লক করেছে।",
    tapToUnmute: "সাউন্ড চালু করুন",
    dismissAlarm: "বন্ধ করুন",
    openStickyNote: "স্টিকি নোট খুলুন",
    turnOffAlarm: "এলার্ম বন্ধ করুন",
    alarmLeaveWarning: "এখন একটি এলার্ম চলছে। বের হওয়ার আগে এটি বন্ধ করুন।",
    projects: "প্রজেক্ট",
    clear: "মুছুন",
    writeYourNotesHere: "এখানে আপনার নোট লিখুন...",

    // Projects
    noProjectsYet: "এখনো কোনো প্রজেক্ট নেই",
    createFirstProject: "আপনার কাজগুলো সংগঠিত করতে প্রথম প্রজেক্ট তৈরি করুন",
    addProject: "প্রজেক্ট যোগ করুন",
    createNewProject: "নতুন প্রজেক্ট তৈরি করুন",
    projectTitle: "প্রজেক্টের শিরোনাম",
    enterProjectTitle: "প্রজেক্টের শিরোনাম লিখুন...",
    description: "বিবরণ (ঐচ্ছিক)",
    enterProjectDescription: "প্রজেক্টের বিবরণ লিখুন...",
    createProject: "প্রজেক্ট তৈরি করুন",
    cancel: "বাতিল",
    editProject: "প্রজেক্ট সম্পাদনা",
    saveChanges: "পরিবর্তন সংরক্ষণ",
    deleteProject: "প্রজেক্ট মুছুন",
    areYouSureDeleteProject: "আপনি কি নিশ্চিত যে আপনি মুছতে চান",
    thisActionCannotBeUndone: "এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।",

    // Todos
    addNewTodo: "নতুন টুডু যোগ করুন...",
    noTodosYet: "এখনো কোনো টুডু নেই। উপরে একটি যোগ করুন!",
    addTodo: "টুডু যোগ করুন",
    low: "নিম্ন",
    medium: "মধ্যম",
    high: "উচ্চ",
    progress: "অগ্রগতি",
    completed: "সম্পন্ন",

    // Tabs
    shortcuts: "শর্টকাট",
    startByAddingFirstShortcut: "আপনার প্রথম শর্টকাট যোগ করে শুরু করুন।",
    addShortcut: "শর্টকাট যোগ করুন",
    shortcutOptions: "শর্টকাট অপশন",
    keyboardShortcut: "কীবোর্ড শর্টকাট",
    recordShortcut: "শর্টকাট রেকর্ড করুন",
    pressKeys: "যেকোনো কী কম্বিনেশন চাপুন...",
    shortcutInUse: "এই শর্টকাটটি ইতিমধ্যে ব্যবহৃত হচ্ছে",
    clearShortcut: "শর্টকাট মুছুন",
    openInNewWindow: "নতুন উইন্ডোতে খুলুন",
    setShortcutDescription:
      "এই ট্যাবে দ্রুত অ্যাক্সেসের জন্য একটি কীবোর্ড শর্টকাট সেট করুন।",
    shortcut: "শর্টকাট",
    resetEverything: "সবকিছু রিসেট করুন",
    resetEverythingDescription:
      "এটি সব ট্যাব, প্রজেক্ট, নোট এবং সেটিংস মুছে ফেলবে। এই কাজটি পূর্বাবস্থায় ফেরানো যাবে না।",
    confirmReset: "আপনি কি নিশ্চিত যে আপনি সবকিছু রিসেট করতে চান?",
    resetWarning:
      "এটি আপনার সব ডেটা স্থায়ীভাবে মুছে ফেলবে যার মধ্যে রয়েছে ট্যাব, প্রজেক্ট, নোট এবং সেটিংস।",

    // Common
    loading: "লোড হচ্ছে...",
    error: "ত্রুটি",
    success: "সফল",
    close: "বন্ধ",
    save: "সংরক্ষণ",
    edit: "সম্পাদনা",
    add: "যোগ",
    remove: "অপসারণ",
    update: "আপডেট",
    create: "তৈরি",
    search: "খুঁজুন",
    filter: "ফিল্টার",
    sort: "সাজান",
    refresh: "রিফ্রেশ",
    back: "পেছনে",
    next: "পরবর্তী",
    previous: "পূর্ববর্তী",
    finish: "শেষ",
    done: "সম্পন্ন",
    ok: "ঠিক আছে",
    yes: "হ্যাঁ",
    no: "না",
  },
} as const;

export const getTranslation = (language: Language, key: string): string => {
  return (
    TRANSLATIONS[language][
      key as keyof (typeof TRANSLATIONS)[typeof language]
    ] || key
  );
};

export const useTranslation = (language: Language) => {
  return (key: string) => getTranslation(language, key);
};
